# Chat command prefix.
command_prefix = "!"

# Command cooldown in seconds.
command_cooldown = 10

# Minecraft server ender pearl view distance in blocks.
# Better to under-estimate than to over-estimate.
# 60 is the default for most server software.
pearl_view_distance = 60

# Minecraft server address.
server_address = "play.vengeancecraft.net:25565"

# Automatically whitelist players that enter visual range.
whitelist_in_range = false

# Disable commands for non-whitelisted players.
whitelist_only = false

# Discord client token for commands and events. (Optional)
# discord_token = ""

# ViaProxy server version. (Optional)
# server_version = ""


[api_server]

# Enable the API server.
enabled = false

# API Server bind address.
# A host of 127.0.0.1 will only be available locally, and port 0 will mean a random port is chosen.
bind_addr = "127.0.0.1:0"


[chat_encryption]

# Encryption key for chat messages. Default is public!
key = "blfrngArk3chG6wzncOZ5A=="

# Encryption response mode.
# Possible values: [`ondemand`, `always`, `never`]
mode = "ondemand"


[users]
