name: Build binaries

on:
  release:
    types: [ created ]

jobs:
  build:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux-aarch64
            target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest

          - name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest

          - name: macOS-aarch64
            target: aarch64-apple-darwin
            runner: macos-latest

          - name: macOS-x86_64
            target: x86_64-apple-darwin
            runner: macos-latest

          - name: Windows-aarch64
            target: aarch64-pc-windows-msvc
            runner: windows-latest

          - name: Windows-x86_64
            target: x86_64-pc-windows-msvc
            runner: windows-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Update Dependencies (Linux)
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt upgrade

      - name: Install Dependencies (Linux-aarch64)
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: sudo apt install gcc-aarch64-linux-gnu

      - name: Update Rust Toolchain
        run: rustup update nightly

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Build Debug Binaries
        run: cargo build --target ${{ matrix.target }}

      - name: Rename Binary and Upload to GitHub Release
        if: ${{ matrix.runner == 'windows-latest' }}
        run: |
          mv target/${{ matrix.target }}/debug/shaysbot.exe ShaysBot-${{ matrix.name }}.exe
          gh release upload ${{ github.ref_name }} ShaysBot-${{ matrix.name }}.exe --clobber

      - name: Rename Binary and Upload to GitHub Release
        if: ${{ matrix.runner != 'windows-latest' }}
        run: |
          mv target/${{ matrix.target }}/debug/shaysbot ShaysBot-${{ matrix.name }}
          gh release upload ${{ github.ref_name }} ShaysBot-${{ matrix.name }} --clobber